### ISSUE TITLE
beh.sas dropping too many format files

### ISSUE THREAD

**Issue by JaniceShu** [SKDE-Analyse/sas_codes#87]
Why do we drop all the format files at the end of beh.sas.  In particular, fmtfil_komnr which was created in bo.sas is deleted.  But we need this as format for kommunenummer, don't we?  The other formats (like kort, kortest) we sometimes use too, so should probably keep them also.

**Comment by arnfinn** [comment]
Usikker. Ble gjort her: [`9f85342` (#83)](https://github.com/SKDE-Analyse/sas_codes/pull/83/commits/9f8534272b68dfbc8934a8448f5c5132ebc7f741)
