### ISSUE TITLE
Vil denne fungere nå, med ny boomraade makro?

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Analyse/sas_codes#99]
https://github.com/SKDE-Analyse/sas_codes/blob/13b3aceb7840b874d0b0dcec194fefd5669e2733/rateprogram/sas/indirekterate.sas#L186

**Comment by Tovjoh** [comment]
Denne makroen brukes ikke av rateprogrammet. Den ble lagd ifbm et atlas, men ble ikke brukt likevel. Indirekte justerte rater blir beregnet i samme program som justerte rater.
